### ISSUE TITLE
pwa builder is not fetching the manifest

### ISSUE THREAD

**Issue by hlpub** [pwa-builder/pwabuilder-manifest-finder#1]
it hangs loading the manifest diagnostics. It happens for any valid pwa url i enter.

**Comment by PedFastTech** [comment]
I am getting the identical symptoms.

**Comment by littlegubs** [comment]
yep, error 500 every time
![image](https://user-images.githubusercontent.com/30618378/108695242-587d7980-7500-11eb-8139-54c8fd620227.png)

**Comment by littlegubs** [comment]
seems fixed now :)

**Comment by davrous** [comment]
Thanks for the report! We fixed it yesterday and added a service health check to avoid being so slow to fix this kind of issues in the future ;)
